---
- hosts: minikube
  tasks:
  - name: Create service of MySQL
    k8s:
        state: present
        definition:
            apiVersion: v1
            kind: Service
            metadata:
              name: mysql
              namespace: blog
            spec:
              selector:
                app: mysql
              ports:
                - protocol: TCP
                  port: 3306
                  targetPort: 3306
    
  - name: Create secret of MySQL
    k8s:
        state: present
        definition:
            apiVersion: v1
            kind: Secret
            metadata:
              name: mysql-secret
              namespace: blog
            data:
              user: aGFraW1yaXpraQ==
              password: bWlkdHJhbnMtZGV2b3Bz
              root_password: dG9vcg==
              
  - name: Create deployment of MySQL
    k8s:
        state: present
        definition:
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: mysql
              namespace: blog
              labels: 
                app: mysql
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: mysql
              template:
                metadata:
                  labels:
                    app: mysql
                spec:
                  containers:
                  - name: mysql
                    image: mysql:5.7
                    env:
                    - name: MYSQL_ROOT_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: mysql-secret
                            key: root_password
                    - name: MYSQL_DATABASE
                      value: blog
                    - name: MYSQL_USER
                      valueFrom:
                        secretKeyRef:
                            name: mysql-secret
                            key: user
                    - name: MYSQL_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: mysql-secret
                            key: password
                    ports:
                    - containerPort: 3306
                    resources:
                      limits:
                        memory: "512Mi"
                        cpu: "100m"     