---
    - hosts: server1,server2
      become: yes
      become_user: root
      tasks:
        - name: Disable swap memory
          command: swapoff -a
        
        - name: Add Docker GPG key
          apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    
        - name: Add Docker APT repository
          apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

        - name: Install list of packages
          apt:
            name: ['apt-transport-https', 'ca-certificates', 'curl' ,'software-properties-common', 'docker.io']
            update_cache: yes
        
        - name: Setup the Docker daemon to use systemd as the cgroup driver
          shell:
            cmd: |
              cat > /etc/docker/daemon.json <<EOF
              {
                "exec-opts": ["native.cgroupdriver=systemd"],
                "log-driver": "json-file",
                "log-opts": {
                  "max-size": "100m"
                },
                "storage-driver": "overlay2"
              }
              EOF

        - name: Create a systemd directory for Docker
          file:
            path: /etc/systemd/system/docker.service.d
            state: directory
        
        - name: Restart Docker
          systemd:
            state: restarted
            daemon_reload: yes
            name: docker
    
        - name: Add the required GPG key to apt-sources keyring to authenticate the Kubernetes
          apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg
    
        - name: Add Kubernetes to the package manager’s list of sources 
          shell:
            cmd: |
              cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
              deb https://apt.kubernetes.io/ kubernetes-xenial main
              EOF
        
        - name: Install kubeadm, kubelet, and kubectl
          apt:
            name: ['kubeadm', 'kubelet', 'kubectl']
            update_cache: yes

        - name: Initialize the master node
          command: kubeadm init --pod-network-cidr=10.148.0.0/20

        - name: Initialize to access Kubernetes nodes
          command: "{{ item }}"
          with_items: 
            - mkdir -p $HOME/.kube
            - sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
            - sudo chown $(id -u):$(id -g) $HOME/.kube/config

    - hosts: server1
      become: yes
      become_user: root
      tasks:  
        - name: Install Calico on Kubernetes
          command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
    
   