apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openvpn
  namespace: openvpn
  labels:
    app: openvpn
    chart: openvpn-4.2.0
    heritage: Tiller
    release: openvpn
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: openvpn
      release: openvpn
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openvpn
        release: openvpn
    spec:
      containers:
      - command:
        - /etc/openvpn/setup/configure.sh
        image: jfelten/openvpn-docker:1.1.0
        imagePullPolicy: IfNotPresent
        name: openvpn
        ports:
        - containerPort: 443
          name: openvpn
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - nc
            - -z
            - 127.0.0.1
            - "443"
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 2
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 300m
            memory: 128Mi
          requests:
            cpu: 300m
            memory: 128Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        # - mountPath: /etc/openvpn/setup
        #   name: openvpn
        - mountPath: /etc/openvpn/certs
          name: certs
        - mountPath: /etc/openvpn/setup/setup-certs.sh​
          name: openvpn
          subPath: setup-certs.sh
        - mountPath: /etc/openvpn/setup/configure.sh
          name: openvpn
          subPath: configure.sh
        - mountPath: /etc/openvpn/setup/newClientCert.sh
          name: openvpn
          subPath: newClientCert.sh
        - mountPath: /etc/openvpn/setup/openvpn.conf
          name: openvpn
          subPath: openvpn.conf
        - mountPath: /etc/openvpn/setup/revokeClientCert.sh
          name: openvpn
          subPath: revokeClientCert.sh
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: openvpn
        configMap:
          name: openvpn
      - name: certs
        secret:
          secretName: certs
        persistentVolumeClaim:
          claimName: openvpn-data-claim