apiVersion: v1
kind: Service
metadata:
  name: openvpn
  namespace: openvpn
  labels:
    app: openvpn
    chart: openvpn-4.2.0
    heritage: Tiller
    release: openvpn
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: openvpn
    nodePort: 32269
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: openvpn
    release: openvpn
  sessionAffinity: None
  type: LoadBalancer
