apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-tools
  namespace: ${NAMESPACE:=justice}
  labels:
    app: backup-tools
    component: justice
    stage: ${STAGE:=dev}
    tier: backend
spec:
  schedule: "0 */12 * * *"  
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-tools
              image: ${IMAGE_REPO}:${IMAGE_TAG}
              command: ["sh", "/app/awesome_backup.sh"]       
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: backup-tools-variables
                - secretRef:
                    name: backup-tools-secrets
          restartPolicy: Never
          serviceAccount: ${SERVICE_ACCOUNT_NAME:=mongodb-backup-serviceaccount}
          serviceAccountName: ${SERVICE_ACCOUNT_NAME:=mongodb-backup-serviceaccount}