apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backup-tools-secrets
  namespace: ${NAMESPACE:=justice}
  labels:
    app: backup-tools
    component: justice
    stage: ${STAGE:=dev}
    tier: backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ${SECRET_STORE_REF:=cluster-secretstore}
    kind: ClusterSecretStore
  target:
    name: backup-tools-secrets
    creationPolicy: "Owner"
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: ${SSM_PATH}/backup-tools/mongodb_uri
    - secretKey: PG_USERNAME
      remoteRef:
        key: ${SSM_PATH}/postgres/postgresql12_username
    - secretKey: PGPASSWORD
      remoteRef:
        key: ${SSM_PATH}/postgres/postgresql12_password
    - secretKey: PG_HOST
      remoteRef:
        key: ${SSM_PATH}/postgres/postgresql12_address