apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/irsa_ab_dashboard_${CUSTOMER_NAME}_${PROJECT_NAME}_${ENVIRONMENT_NAME}
  labels:
    app.kubernetes.io/name: mongodb-backup-serviceaccount
  name: mongodb-backup-serviceaccount
  namespace: justice