stages:
    - build
    - deploy
  
build-images-staging:
    stage: build
    only:
      - staging
      - tags
    tags:
      - golang
    script:
      - GO111MODULE=on go mod tidy
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./bin/asgard-bivrost cmd/redishttp/main.go
      - docker build -t $REGISTRY:$ENVIRONMENT-v1.$CI_RUNNER_ID .
      - docker push $REGISTRY:$ENVIRONMENT-v1.$CI_RUNNER_ID
      - kcs $K8S_CONFIG_STAGING
      - eval "kubectl patch deploy $DEPLOY_STAGING -n test --patch '{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"image\":\"$REGISTRY:$ENVIRONMENT-v1.$CI_RUNNER_ID\",\"name\":\"$DEPLOY_STAGING\"}]}}}}'"
  
deploy-k8s-staging:
    stage: deploy
    only:
      - staging
      - tags
    tags:
      - golang
    script: 
      - kubectl apply -f $K8S_PATH_STAGING
      - docker rmi $REGISTRY:$ENVIRONMENT-v1.$CI_RUNNER_ID
  
build-images-master:
    stage: build
    only:
      - master
      - merge_request
      - tags
    tags:
      - golang
    script:
      - GO111MODULE=on go mod tidy
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./bin/asgard-bivrost cmd/redishttp/main.go
      - docker build -t $REGISTRY:$ENVIRONMENT-v1.$CI_RUNNER_ID .
      - docker push $REGISTRY:$ENVIRONMENT-v1.$CI_RUNNER_ID
      - kcs $K8S_CONFIG_UAT
      - eval "kubectl patch deploy $DEPLOY_UAT -n core --patch '{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"image\":\"$REGISTRY:$ENVIRONMENT-v1.$CI_RUNNER_ID\",\"name\":\"$DEPLOY_UAT\"}]}}}}'"
  
deploy-k8s-master:
    stage: deploy
    only:
      - master
      - merge_request
      - tags
    tags:
      - golang
    script: 
      - kubectl apply -f $K8S_PATH_UAT
      - docker rmi $REGISTRY:$ENVIRONMENT-v1.$CI_RUNNER_ID
  