apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvpn-data-claim
  namespace: openvpn
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: openvpn
  volumeName: openvpn-data-volume