apiVersion: v1
kind: PersistentVolume
metadata:
  name: openvpn-data-volume
  namespace: openvpn
  labels:
    type: local
spec:
  storageClassName: openvpn
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: openvpn-data-claim
    namespace: openvpn
  hostPath:
    path: "/mnt/data"

