apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: wordpress
  minReplicas: 2 
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50

