apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: blog-rbac
subjects:
- kind: ServiceAccount
  name: default
  namespace: blog
roleRef:
  kind: ClusterRole
  name: kuberesolver-rbac
  apiGroup: rbac.authorization.k8s.io