apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql:3306
        - name: WORDPRESS_DB_NAME
          value: blog
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
                name: mysql-secret
                key: user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
                name: mysql-secret
                key: password
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"